name: phylo_pipeline
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  # --- genome download (step 1) ---
  - biopython>=1.81
  # --- genome annotation (step 2) ---
  - bakta>=1.9
